### ISSUE TITLE
[Bug]: Failed to post, reply button infinite spinning

### ISSUE THREAD

**Issue by SeverinAlexB** [pubky/pubky-beta#789]
### Describe the bug

I wanted to reply, but the reply button kept spinning indefinitely. Lots of console log errors. A page refresh fixed the issue but still posting here because I had to rewrite my whole reply.

### Reproduce

No idea? Check video

### Screenshots / Recording

https://github.com/user-attachments/assets/22e7aa7b-901c-48c2-b4e4-792f241f5526

### Web Browser

Newest Brave browser

### Pubky App Version

Staging

### Console log output

```shell
Tons of these errors:

2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
nexus.staging.pubky.app/v0/user/operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo?viewer_id=ggz68z9y6pty6jmezinq33amb616j7zscigr6uxsbojeb64kt8hy:1 
        
        
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
2855-08843724afcd8acf.js:1 Error fetching participants: TypeError: Failed to fetch
    at l (518-ed8ca039680c668f.js:1:200069)
    at page-5400722e0ba10228.js:1:3636
    at Array.map (<anonymous>)
    at I (page-5400722e0ba10228.js:1:3621)
    at page-5400722e0ba10228.js:1:3949
    at oT (87c73c54-5aa0edeb164d80df.js:1:81813)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97505)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:98600)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
    at o9 (87c73c54-5aa0edeb164d80df.js:1:97485)
    at o5 (87c73c54-5aa0edeb164d80df.js:1:97389)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2855-08843724afcd8acf.js:1 Error fetching participants: Error: Failed to fetch user profile
    at l (518-ed8ca039680c668f.js:1:200137)
    at async Promise.all (index 0)
    at async I (page-5400722e0ba10228.js:1:3601)
push.19513.window.console.error @ 2855-08843724afcd8acf.js:1
operrr8wsbpr3ue9d4qj41ge1kcc6r7fdiy6o3ugjrrhi4y77rdo:1 
        
        
Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
```

**Comment by flaviomoceri** [comment]
is this still a issue or we can close it?

**Comment by SeverinAlexB** [comment]
So far so good. This happened once only so can't judge if the bug is still there.

**Comment by flaviomoceri** [comment]
I close it. If necessary please reopen it
